# Generated by Django 6.1 on 2026-09-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='dexNum',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
