# Generated by Django 6.1 on 2026-09-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pokemon_dexnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='gen',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
