# Generated by Django 6.1 on 2026-09-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pokemon_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='cover',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
